### ISSUE TITLE
更好的 READNE.MD

### ISSUE THREAD

**Issue by ItzMiracleOwO** [RadishTeam/RadishBot#11]
希望可以加入 [CodeFactor](https://www.codefactor.io) 的代碼診斷，引入 Github Action 中的 eslint 保證代碼質量...
還有其他的 Badges 可以參考 [我的專案](https://github.com/ItzMiracleOwO/WardDashboard) 裏面的 README.md

GitHub Action Eslint 例子
```
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
```
